- bindings/nostr-ffi/src/event/builder.rs
- bindings/nostr-ffi/src/subscription.rs
- crates/nostr-sdk/src/client/blocking.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/examples/bip340.rs
- crates/nostr/examples/delete_event.rs
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/mod.rs
- crates/nostr/src/event/tag.rs
- crates/nostr/src/lib.rs
- crates/nostr/src/message/relay.rs
- crates/nostr/src/message/subscription.rs
- crates/nostr/src/util/nips/nip13.rs
- crates/nostr/src/util/nips/nip26.rs
This changes the type of event ID in some places from `XOnlyPublicKey` to `Sha256Hash`, like for example in `bindings/nostr-ffi/src/subscription.rs` :
https://github.com/ok300/nostr-rs-sdk/commit/d81d45ec236deeaae2b0130ca5f4f34b0b9383f1#diff-12a81a45d00b2eb02fa872873da2ed071b0db52e412bf2cd2fa97e5b5cf0f972
To keep things consistent, I also replaced other uses of `sha256::Hash` with the alias `Sha256Hash`.
> Change id type from XOnlyPublicKey to Sha256Hash

- bindings/nostr-ffi/src/event/kind.rs
- bindings/nostr-ffi/src/nostr.udl
- crates/nostr/src/event/kind.rs
Increase event kind range from u16 to u64.
Some recent events have an ID that's way outside the current Kind range, like this one:
```json
{
"id":"0f71974d06ceda0024317b9a370de6d904cd5038e81c27087335308486d64e07",
"pubkey":"543210b5f6c3071c3135d850449f8bf91efffb5ed1153e5fcbb2d95b79262b57",
"created_at":1671154736,
"kind":641204,
"tags":[["sequence","825"],["height","767602"]],
"content":"{\"document_uid\":\"9827d8ede1572958ef01b67aee20618be038af2976b9aee0b175c3624e93b997\",\"patch_uid\":\"2d0a805f187eff484a172a68fa98ff6c0337abfe8c4e8020905aa3665016cc41\",\"operation\":2,\"reason\":\"\",\"sequence\":13}",
"sig":"5300d608310b655c7f8d9ebfc8e1aca0e183dbca68e682df4ca72eec440d1ebb34ae807840e14f83bf9c5ea6a4c61cd99b3d9bae553746d4332f006ef98f77f9"
}
```
Even though …
> Increase event kind range

- crates/nostr-sdk/Cargo.toml
- crates/nostr-sdk/README.md
- crates/nostr/Cargo.toml
- crates/nostr/README.md
- crates/nostr/src/util/nips/mod.rs
The reqwest dependency breaks the wasm32-unknown-unknown build target. I've moved the two nips that use reqwest behind feature flags
> WASM support

- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/pool.rs
Increase the tokio channel sizes from 64 to 1024.
These channels are used to buffer the received messages and notifications. If they are not consumed (via `client.notifications()`) fast enough, the receiving loop will fail with [RecvError::Lagged](https://docs.rs/tokio/latest/tokio/sync/broadcast/error/enum.RecvError.html#variant.Lagged), indicating the receiver "lagged" behind and some events got lost.
In my case, the consumer was parsing the message and adding it to a DB transaction. For more complex messages, this took a few milliseconds. That was slow enough to lead to lost messages.
The receive loop:
```rust
let mut notifications = client.notifications();
loop {
match notifications.recv().await {
Ok(notification) => {
// process it
}
Err(e) => {
match e {
RecvError::Closed => { …
```
> Increase channel size for receiving events and sending notifications

- crates/nostr/Cargo.toml
- crates/nostr/src/event/builder.rs
- crates/nostr/src/util/time.rs
When building for the wasm32-unknown-unknown target, calling `Instant::now()` panics because the web browser environment has no access to the system clock. [This crate](https://crates.io/crates/instant) is a drop-in replacement for `std::time::Instant` that works for WASM. 
I've added the instant crate as a dependency only when compiling for wasm. An alternative is to add it as a general dependency and remove the `#[cfg(not(target_arch = "wasm32"))]` directives. When building for any other target than wasm `instant::Instant` is just a type alias to `std::time::Instant`
> time support for wasm target

- crates/nostr/examples/nip11.rs
- crates/nostr/src/nips/nip11.rs
Supersedes #20.
Three related changes in NIP11:
- allow passing WS(S) scheme to relay information document retrieval
- make all fields in the information document optional according to spec
- remove unspecified field `id` from the document
> nostr: nip11: make all fields optional and accept wss://

- crates/nostr/src/event/id.rs
When `Sha256Hash` was wrapped by `EventId`, `Hash` derivation was missing.
> Add Hash derivation to EventId

- crates/nostr/src/nips/nip26.rs
Add `verify_delegation_signature()`, to match `sign_delegation()`.
Useful for verifying a signature (by delegatee) and also for testing.
Also added tests.
>  Add verify_delegation_signature()

- bindings/nostr-nodejs/src/event/builder.rs
- bindings/nostr-sdk-nodejs/src/client/mod.rs
- crates/nostr-sdk/src/client/blocking.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/src/event/builder.rs
Removes the Option<> around the relay url parameter for kind 42 events. NIP-28 defines that kind 42 events SHOULD use NIP-10 marked "e tags". NIP-10 defines "relay-url" to be NOT optional.
I have not tested this change in any external implementation but the project builds just fine and the existing tests are running successfully.
The commit wasn't signed as I haven't really set up a PGP key yet. If it's mandatory for contributing, I can get that set up over the next couple of days.
**Fixed**
- Made relay-url mandatory for kind 42 events
> Make relay url mandatory for kind 42 events

- bindings/nostr-nodejs/src/nips/nip26.rs
- crates/nostr/src/nips/nip26.rs
Add support for complete NIP-26 delegation tags: create a delegation tag, validate a delegation tag.
- API change of (recently added) `verify_delegation_signature`:  First parameter is only public key, not keypair, as secret key is NOT needed for validation.
- New NIP-26 delegation tag support: create, parse, validate a delegation tag (`nip26::DelegationTag`)
- API change in (recently added) `nip26::verify_delegation_signature()` (first parameter changed from KeyPair to XOnlyPublicKey).
> Add NIP-26 delegation tag support

- crates/nostr/src/message/subscription.rs
This PR is to fix the doc comments for Filter::id. Ref: <https://github.com/nostr-protocol/nips/blob/master/01.md>.
```json
{
"ids": <a list of event ids or prefixes>,
"authors": <a list of pubkeys or prefixes, the pubkey of an event must be one of these>,
"kinds": <a list of a kind numbers>,
"#e": <a list of event ids that are referenced in an "e" tag>,
"#p": <a list of pubkeys that are referenced in a "p" tag>,
"since": <an integer unix timestamp, events must be newer than this to pass>,
"until": <an integer unix timestamp, events must be older than this to pass>,
"limit": <maximum number of events to be returned in the initial query>
}
```
> nostr: fix Filter::id(s) doc comments

- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/pool.rs
- crates/nostr/examples/tweet.rs
- crates/nostr/src/nips/nip46.rs
Should the code a bit more readable and concise
> Code cleanup: use .. instead of _ in deconstructions

- crates/nostr/src/message/client.rs
As of nostr v0.19.1 REQ events in form of
``` json
[
"REQ",
"id",
{
"ids": [],
"kinds": [
1,
42
]
},
{
"kinds": [
1,
5,
6,
7,
9735
],
"#e": []
}
]
```
return error _MessageHandleError::InvalidMessageFormat_
This PR fixes this behavior
> Include rest of the REQ event as filters

- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/pool.rs
I was playing a bit with nostr-sdk and noticed that multiple independent clients connected to the same relay start getting messages from each others subscriptions.  
[Reproduced it minimally here](https://gist.github.com/arkaitzj/aaf87af9fb64a62f71f0b9b20c3ad385)
It seems to stem from the fact that there is a single, [global Subscription object for everyone](https://github.com/rust-nostr/nostr/blob/228b00c7671dfa0b41e862876af151572767d8ef/crates/nostr-sdk/src/relay/pool.rs#L26).  
I understand, correct me if I am wrong, that this is not the expected behaviour?
I added changes that allow relay objects, one per client, to have their own filters, with their own ids and use them on every reconnection.  
Pools also keep their own copy of the subscription object to supply it to new relays …
> Multiple clients pointing to the same relay share subscriptions

- crates/nostr/src/message/relay.rs
There was no implementation for deserialization of `RelayMessage::Auth`
> Add deserialization for RelayMessage::Auth

- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/tag.rs
How I get the e and p tags is pretty ugly, not sure if there is a cleaner way to do it. Would be nice if there were some helper functions on `Event` to give it a `TagKind` and it returns all the `Tag`s.
Sorry for double PR, screwed up something with #71
Added some helper functions for creating zap events.
> Create EventBuilder helper for zaps

- bindings/nostr-ffi/src/contact.rs
- bindings/nostr-js/src/types/contact.rs
- bindings/nostr-nodejs/src/types/contact.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/tag.rs
- crates/nostr/src/prelude.rs
- crates/nostr/src/types/contact.rs
Since the relays tag is part of what is signed, the exact string is important. I added this `RelayUrl` struct to keep both a `Url` and the original string. However, I'm not convinced its needed and may just be simpler to be a string like relays in the contact list tag. Let me know what you think is better as the currant implementation will make signature verification fail when a zap is serialize/deseralized.
Add
- `RealyUrl` struct
Change
- Relays Tag from `Vec<Url>` to `Vec<RelayUrl>`
> Fix: Relay Tag seralization 

- crates/nostr/src/event/builder.rs
The amount tag doesn't seem to be a part of the kind 9735 event so I removed it. Seems like this was confused with the kind 9734 event which does actually have the amount tag.
```md
- "amount" parameter from zap receipt event builder
```
> Remove amount tag from zap receipt event builder

- crates/nostr/src/event/tag.rs
Adds the lnurl tag, commonly used in NIP-57 [kind 9734 events](https://github.com/nostr-protocol/nips/blob/master/57.md#appendix-a-zap-request-event) (Zaps).
I have not signed my commit as I haven't set up a PGP key at the moment.
```md
- LNURL event tag
```
> Add lnurl tag

- bindings/nostr-sdk-js/src/client/mod.rs
- bindings/nostr-sdk-nodejs/src/client/mod.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/pool.rs
Awesome crate!
I found the behavior of `req_events_of` to be a bit confusing. At first, I didn't realize that it stops pushing events onto the client `notifications()` channel once `EOSE` has been received from the relay. After digging around the code and actually looking at the examples, I saw that `subscribe` is the better method to use for real-time streaming of events.
Perhaps the method should have a different name in the future? I'm not exactly sure what it could be, but I'm hoping this addition to the docs will clarify for users.
> docs: clarify req_events_of behavior

- crates/nostr/src/types/metadata.rs
In metadata, both `displayName` and `display_name` are common. The library should be able to parse both versions.
Changed
- `displayName` in metadata also accepted besides `display_name`
> nostr: Also accept `displayName` in metadata

- crates/nostr-sdk/src/relay/pool.rs
Simple PR documenting one distinction between `RelayPoolNotification::Event` and `RelayPoolNotification::Message`.
> Add more docs for RelayPoolNotification

- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/lib.rs
- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/options.rs
- crates/nostr-sdk/src/relay/pool.rs
> sdk: add `FilterOptions`

- bindings/README.md
Links now direct to `crates/nostr` instead of `bindings/crates/nostr` which does not exist.
> ffi: fix links in `bindings` README.md

- bindings/nostr-ffi/src/event/builder.rs
- bindings/nostr-ffi/src/nostr.udl
- bindings/nostr-js/src/event/builder.rs
- bindings/nostr-sdk-ffi/src/nostr_sdk.udl
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/src/event/builder.rs
> Rename EventBuilder arg

- crates/nostr/src/key/mod.rs
This isn't a silver bullet for clearing SecretKey from memory it will help.
* [ x ] I've signed all my commits
* [ x ] I followed the [contribution guidelines](../CONTRIBUTING.md)
* [ x ] I ran `make precommit` before committing
> nostr: attempt to erase `SecretKey` when dropped

- crates/nostr/src/nips/nip11.rs
Adds the extra fields defined in NIP11
Closes #165 
I added the tests to make sure the serializing and deserializing worked the way we need them to since the retention list can be integers or a list of two integers.
Adds the extra fields defined in NIP11
> add extra nip11 fields

- crates/nostr-sdk/examples/client-with-opts.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/options.rs
Small improvement to have in `RelayOptions` also a `retry_sec `field to use for custom retry time for connection to relay.
Duration is in seconds and default is left as before to 10 secs
Not tested at the moment. Will try ASAP, need to check if different retry time is effective.
* [ x] I've signed all my commits
* [ x] I followed the [contribution guidelines](../CONTRIBUTING.md)
> Custom time of reconnect options added

- crates/nostr/src/event/id.rs
For consistency with `secp256k1::XOnlyPublicKey`, which also [implements](https://docs.rs/secp256k1/latest/src/secp256k1/key.rs.html#1119-1131) it. This is to make it a little easier to work with the `GenericTagValue` enum.
> nostr: impl `fmt::LowerHex` for `EventId`

- crates/nostr/src/message/subscription.rs
An attempt to make it fall more in line with the restrictions laid out in NIP-01. I don't know whether this should be restricted further, because at that point I think it would be best to put standardized tags into their own fields within the `Filter` struct.
> nostr: filter out `GenericTagValue` variants that do not adhere to the spec

- crates/nostr/src/message/subscription.rs
Present `tag_match()` implementation returns always `true` if an event has empty `tags`.
This causes false positives from `match_event()`.
If a tag filter is not empty and `tags` in event is empty, then `tag_match()` should return `false`.
I think we can safely omit L660-662 from my patch, because, in such case `idx.get()` will return `None` for any `tagname` and it results in `false` for `tag_match()`.
- Make `tag_match()` return `false` if a tag filter is not empty and `tags` in event is empty.
> Fix tag_match behavior for events with empty tags

- crates/nostr/src/nips/nip04.rs
Since encrypt takes a `AsRef<[u8]>` you can pass in a byte array but `decrypt` only gives you the option to get the UTF-8 encoded string in return. This adds `decrypt_to_bytes` so you can get the raw bytes if you don't wish to use the string.
> NIP-04: Allow decrypting to raw bytes

- crates/nostr/src/nips/nip19.rs
Add `Nip19` for decoding any bech32 nip19 nostr object in a single go.
This is important when you don't necessarily know the object you are
decoding, such as when someone enters an object into a search field.
I don't use pgp anymore. Please judge my submission based on my code and not my identity.
> Add `Nip19` for decoding any nip19 object

- bindings/nostr-ffi/src/types/metadata.rs
- crates/nostr/src/types/metadata.rs
Found this when trying to parse @dergigi's metadata, it has some fields that are not strings so it would fail. This makes it so it skips over non-string items that we don't understand
example:
```
{
"id": "6cae3971652c112a5cf75042cc98c4bb186b8a9b03577c244364bc884bd5f58e",
"pubkey": "6e468422dfb74a5738702a8823b9b28168abab8655faacb6853cd0ee15deee93",
"created_at": 1701643922,
"kind": 0,
"tags": [],
"content": "{\"reactions\":false,\"about\":\"building opensats.org • writing 21waysbook.com • shipping sovereignengineering.io • painting twentyone.world • maintaining bitcoin-resources.com & nostr-resources.com • starting toomanyprojects.xyz 🥔\",\"picture\":\"https://dergigi.com/assets/images/avatar-laser.jpg\",\"damus_donation_v2\":0,\"banner\":\"https://cdn.nostr.build/i/0aeb7560c271bbb1cef0076 …
```
> Fix parsing metadata with non-string types

- crates/nostr-sdk/examples/nip47.rs
An example of how to use NIP-47 from rust-nostr
I hope this is helps people to easily get started sending payments with NWC.
It feels a bit low-level for the SDK, but it relies on the SDK to connect to the relay. Maybe a higher-level NIP-47 library could be added in the future?
> doc: Add nip47 pay_invoice example

- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/client/zapper.rs
Using the `ClientSigner` in mutiny now want to be able to sign arbitrary events, need this to be public
> Make nostr-sdk signing events public

- bindings/nostr-sdk-ffi/src/client/mod.rs
- bindings/nostr-sdk-ffi/src/relay/mod.rs
- bindings/nostr-sdk-ffi/src/relay/options.rs
- bindings/nostr-sdk-js/examples/client.js
- bindings/nostr-sdk-js/src/client/mod.rs
- crates/nostr-sdk/README.md
- crates/nostr-sdk/examples/client.rs
- crates/nostr-sdk/examples/get-events-of.rs
- crates/nostr-sdk/examples/subscriptions.rs
- crates/nostr-sdk/src/client/blocking.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/client/options.rs
- crates/nostr-sdk/src/client/signer/nip46.rs
- crates/nostr-sdk/src/client/zapper.rs
- crates/nostr-sdk/src/relay/mod.rs
- crates/nostr-sdk/src/relay/options.rs
- crates/nostr-sdk/src/relay/pool.rs
- crates/nostr-sdk/src/relay/stats.rs
> sdk: allow to send/get msgs and events to/from specific relays

- crates/nostr/src/nips/nip47.rs
Seems like alby is trying these requests without the params empty object which is understandable, this will better handle
> Handle no nwc request params better

- crates/nostr/src/nips/nip57.rs
Working on adding public/private zaps for mutiny. Since we support the NIP-07 signer we need to be able to create private zap events manually, to do so we need this function public.
Also would like to make it so `private_zap_request` doesn't take in a `&Keys`, seems like it is only needed for `create_encryption_key` but don't really see why it is done that way, could just use `Keys::generate`, I guess the main reason is so we can decrypt it ourself
> Make encrypt_private_zap_message pub

- bindings/nostr-ffi/src/nips/nip57.rs
- crates/nostr/src/nips/nip57.rs
The previous function only allowed decrypting private zaps we sent, not received. This makes it so it should be able to handle both
> Better functions for handling decrypting private zaps

- bindings/nostr-ffi/src/event/builder.rs
- bindings/nostr-js/src/event/builder.rs
- bindings/nostr-sdk-ffi/src/client/mod.rs
- bindings/nostr-sdk-js/src/client/mod.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/src/event/builder.rs
* Add `k` tag
* Expose `like`, `dislike` and `reaction` in `nostr-sdk-ffi`
Closes #322
> nostr: update `EventBuilder::reaction` constructor

- crates/nostr/src/event/unsigned.rs
Not sure if this is the best way about going about this. Want to take a signed event and modify it. My plan is to convert to an unsigned event, modify it as I need, recalc event id, and then sign it
> Add impl From<Event> for UnsignedEvent

- bindings/nostr-js/src/event/builder.rs
- bindings/nostr-js/src/event/mod.rs
- bindings/nostr-js/src/event/tag.rs
- bindings/nostr-js/src/key/public_key.rs
- bindings/nostr-js/src/nips/mod.rs
- bindings/nostr-js/src/nips/nip01.rs
- bindings/nostr-js/src/nips/nip15.rs
- bindings/nostr-js/src/nips/nip47.rs
- bindings/nostr-js/src/nips/nip53.rs
- bindings/nostr-js/src/nips/nip57.rs
- bindings/nostr-js/src/nips/nip65.rs
- bindings/nostr-js/src/nips/nip90.rs
- bindings/nostr-js/src/nips/nip94.rs
- bindings/nostr-js/src/nips/nip98.rs
- crates/nostr/src/nips/nip53.rs
Complete `EventBulder` with missing constructor
> js(nostr): complete `EventBuilder`

- bindings/nostr-ffi/src/event/builder.rs
- bindings/nostr-ffi/src/event/kind.rs
- bindings/nostr-ffi/src/event/tag.rs
- bindings/nostr-ffi/src/nips/mod.rs
- bindings/nostr-ffi/src/nips/nip01.rs
- bindings/nostr-ffi/src/nips/nip51.rs
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/kind.rs
- crates/nostr/src/event/tag.rs
- crates/nostr/src/nips/mod.rs
- crates/nostr/src/nips/nip51.rs
> nostr: complete NIP51

- CHANGELOG.md
- crates/nostr/src/event/tag.rs
- crates/nostr/src/types/filter.rs
* Remove `impl<'de> Deserialize<'de> for GenericTagValue`
* Remove `impl<S> From<S> for GenericTagValue`
* Partially revert 526dbfdf4dfbf7b8039b422aee864179ad430a8f
https://github.com/rust-nostr/nostr/issues/372
> nostr: construct `GenericTagValue` based on `SingleLetterTag` in `deserialize_generic_tags`

- crates/nostr-relay-pool/src/relay/internal.rs
start to listen for OK msg immediately before event is sent
this prevents the OK msg from being recieved
before we start listening for it
this bug was introduced in v0.28 and discovered when upgrading
v0.27 ~> v0.29 in ngit (https://https://gitworkshop.dev/ngit)
as it caused many intergration tests to fail
> pool: fix spurious send_event timeout error

- bindings/nostr-js/README.md
The commit replaces incorrect function calls on the keys object in the README's code example, instead referencing them as properties. This aligns the documentation's example accurately with the implementation of public and secret key methods.
> Correct key method calls in README example

- bindings/nostr-sdk-js/src/database.rs
This commit introduces an asynchronous save_event function within database.rs in the nostr-sdk-js bindings. This new method enhances the previous 'inner' save_event functionality by offering improved error handling.
> Add asynchronous save_event method to database.rs

- crates/nostr/src/event/kind.rs
The Kind enum in the nostr event kind module has been refactored to use a macro function 'kind_variants!', drastically reducing its length. This macro takes enum cases in the form 'name => value' and generates corresponding enum entries. This results in more efficient and readable code, as well as a more manageable enum structure.
> Refactor Kind enum to use a macro in nostr event kind module

- crates/nostr/src/nips/nip49.rs
so that decryption time can be estimated and
applications can warn users if needed
> nostr: expose nip49 log_n

- CHANGELOG.md
- bindings/nostr-sdk-ffi/bindings-python/README.md
- bindings/nostr-sdk-ffi/bindings-python/examples/blacklist.py
- bindings/nostr-sdk-ffi/bindings-python/examples/client.py
- bindings/nostr-sdk-ffi/bindings-python/examples/metadata.py
- bindings/nostr-sdk-ffi/src/client/mod.rs
- bindings/nostr-sdk-ffi/src/client/options.rs
- bindings/nostr-sdk-ffi/src/pool/mod.rs
- bindings/nostr-sdk-ffi/src/relay/mod.rs
- bindings/nostr-sdk-js/examples/get-events-of.js
- bindings/nostr-sdk-js/src/client/mod.rs
- bindings/nostr-sdk-js/src/client/options.rs
- bindings/nostr-sdk-js/src/pool/mod.rs
- bindings/nostr-sdk-js/src/relay/mod.rs
- crates/nostr-relay-pool/src/pool/internal.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-relay-pool/src/relay/internal.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-sdk/examples/blacklist.rs
- crates/nostr-sdk/examples/get-events-of.rs
- crates/nostr-sdk/examples/nip65.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/client/options.rs
- crates/nostr-sdk/src/client/zapper.rs
- crates/nostr-sdk/src/lib.rs
* `Relay::get_events_of` and `RelayPool::get_events_of` will get events only from remote relay/s
* `Client::get_events_of` allow to choose the source of events: `database`, `relays` or `both`
> Rework `get_events_of` methods

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/relay/mod.rs
- bindings/nostr-sdk-ffi/src/relay/options.rs
- bindings/nostr-sdk-js/src/relay/mod.rs
- bindings/nostr-sdk-js/src/relay/options.rs
- crates/nostr-relay-pool/src/lib.rs
- crates/nostr-relay-pool/src/pool/inner.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-relay-pool/src/relay/options.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr-sdk/src/lib.rs
* Add `ReqExitPolicy`
* Deprecate `FilterOptions`
@dluvian
> pool: rename `FilterOptions` to `ReqExitPolicy`

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/client/mod.rs
- bindings/nostr-sdk-ffi/src/relay/mod.rs
- bindings/nostr-sdk-js/src/client/mod.rs
- bindings/nostr-sdk-js/src/relay/mod.rs
- crates/nostr-cli/src/main.rs
- crates/nostr-connect/src/client.rs
- crates/nostr-connect/src/signer.rs
- crates/nostr-relay-pool/examples/pool.rs
- crates/nostr-relay-pool/src/pool/constants.rs
- crates/nostr-relay-pool/src/pool/inner.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-relay-pool/src/relay/error.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-relay-pool/src/relay/status.rs
- crates/nostr-relay-pool/src/shared.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nwc/src/lib.rs
Closes https://github.com/rust-nostr/nostr/issues/624
> Add `try_connect` methods

- bindings/nostr-sdk-ffi/android/build-aar.sh
The UPX compression is known to cause issues on `x86` devices for certain Android API levels (e.g., API 30). Since `x86` devices constitute a very small percentage of the Android market (<1%, see links below), apps are unlikely to be shipped for this architecture and are typically used only for testing purposes. Therefore, compress only the ARM (`arm64-v8a` and `armeabi-v7a`) and `x86_64` libraries.
* https://android.stackexchange.com/questions/186334/what-percentage-of-android-devices-runs-on-x86-architecture
* https://web.archive.org/web/20170808222202/http://hwstats.unity3d.com:80/mobile/cpu-android.html
Closes https://github.com/rust-nostr/nostr/issues/703
> ffi: compress only ARM and x86_64 libraries when building the AAR

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nostr-sdk-ffi/Cargo.toml
- bindings/nostr-sdk-ffi/android/lib/build.gradle.kts
- bindings/nostr-sdk-ffi/python/examples/custom-websocket-client.py
- bindings/nostr-sdk-ffi/src/client/builder.rs
- bindings/nostr-sdk-ffi/src/error.rs
- bindings/nostr-sdk-ffi/src/lib.rs
- bindings/nostr-sdk-ffi/src/protocol/signer/custom.rs
- bindings/nostr-sdk-ffi/src/transport/mod.rs
- bindings/nostr-sdk-ffi/src/transport/websocket.rs
- crates/nostr-relay-builder/src/local/inner.rs
- crates/nostr-relay-pool/src/lib.rs
- crates/nostr-relay-pool/src/relay/error.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-relay-pool/src/shared.rs
- crates/nostr-relay-pool/src/stream.rs
- crates/nostr-relay-pool/src/transport/error.rs
- crates/nostr-relay-pool/src/transport/mod.rs
- crates/nostr-relay-pool/src/transport/websocket.rs
- crates/nostr-sdk/src/client/builder.rs
- crates/nostr-sdk/src/client/mod.rs
Allow using custom websocket clients. Add `ClientBuilder::websocket_transport`.
Closes https://github.com/rust-nostr/nostr/issues/721 
Ref https://github.com/rust-nostr/nostr/issues/650#issuecomment-2578901221 
Ref https://github.com/rust-nostr/nostr/issues/650#issuecomment-2595771489
> pool: add WebSocket transport abstraction

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/nips/mod.rs
- bindings/nostr-sdk-ffi/src/protocol/nips/nip22.rs
- crates/nostr/src/event/tag/list.rs
- crates/nostr/src/nips/mod.rs
- crates/nostr/src/nips/nip22.rs
> nostr: add `nip22::extract_root` and `nip22:extract_parent`

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/event/builder.rs
- bindings/nostr-sdk-js/src/protocol/event/builder.rs
- crates/nostr/src/event/builder.rs
Optionally allow self-tagging (`p` tag) when building events.
Closes https://github.com/rust-nostr/nostr/issues/736
> nostr: add `EventBuilder::allow_self_tagging`

- CHANGELOG.md
- Cargo.lock
- contrib/scripts/check-crates.sh
- crates/nostr-lmdb/Cargo.toml
- crates/nostr-lmdb/src/lib.rs
- crates/nostr-lmdb/src/store/error.rs
- crates/nostr-lmdb/src/store/ingester.rs
- crates/nostr-lmdb/src/store/lmdb/mod.rs
- crates/nostr-lmdb/src/store/mod.rs
* lmdb: bump MSRV to 1.72.0
* lmdb: use event ingester
* lmdb: avoid spawning thread for read methods
* lmdb: avoid long-lived read txn when ingesting event
> lmdb: event ingester and other improvements 

- crates/nostr-sdk/src/client/error.rs
- crates/nostr-sdk/src/client/mod.rs
* Improve send private msg error
* Refactor checking and updating of outdated gossip public keys
* Avoid cloning of inbox relay urls when sending gossip event
* Don't try to get the relay lists of the gift-wrap's author, since the used keypair is randomized
> sdk: improvements to gossip logic

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/event/tag/list.rs
- bindings/nostr-sdk-ffi/src/protocol/nips/nip21.rs
- bindings/nostr-sdk-js/src/protocol/event/tag/list.rs
- crates/nostr/src/event/tag/list.rs
- crates/nostr/src/nips/nip19.rs
- crates/nostr/src/nips/nip21.rs
- justfile
- Add `nip21::extract_from_text`
- Add `Tags::from_text`
Closes https://github.com/rust-nostr/nostr/issues/751
> nostr: helpers to extract `nostr:` URIs from text

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/nips/nip01.rs
- bindings/nostr-sdk-ffi/src/protocol/nips/nip19.rs
- bindings/nostr-sdk-ffi/src/protocol/nips/nip21.rs
- bindings/nostr-sdk-js/src/protocol/nips/nip01.rs
- bindings/nostr-sdk-js/src/protocol/nips/nip19.rs
- crates/nostr/src/event/tag/list.rs
- crates/nostr/src/nips/nip01.rs
- crates/nostr/src/nips/nip19.rs
- crates/nostr/src/nips/nip21.rs
- Add `Nip19Coordinate` struct
- Remove `relays` from `Coordinate` struct
- Add `Coordinate::verify` method
- Update coordinate parsing constructors to take `&str`
Closes https://github.com/rust-nostr/nostr/issues/759
> nostr: refine coordinate

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/event/tag/mod.rs
- bindings/nostr-sdk-ffi/src/protocol/event/tag/standard.rs
- bindings/nostr-sdk-js/src/protocol/event/tag/mod.rs
- crates/nostr/src/event/tag/mod.rs
- crates/nostr/src/event/tag/standard.rs
- Add `TagStandard::Client` variant
- Add `Tag::client` constructor
Closes https://github.com/rust-nostr/nostr/issues/750
> nostr: add client tag support

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/event/builder.rs
- bindings/nostr-sdk-ffi/src/protocol/event/tag/standard.rs
- bindings/nostr-sdk-ffi/src/protocol/nips/nip34.rs
- bindings/nostr-sdk-js/src/protocol/event/builder.rs
- bindings/nostr-sdk-js/src/protocol/nips/nip34.rs
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/tag/standard.rs
- crates/nostr/src/nips/nip34.rs
Fix NIP34 event construction according to <https://github.com/nostr-protocol/nips/blob/ea36ec9ed7596e49bf7f217b05954c1fecacad88/34.md> revision.
Closes https://github.com/rust-nostr/nostr/issues/758
> nostr: fix NIP34 event construction according to last rev

- bindings/nostr-sdk-ffi/src/protocol/event/builder.rs
- bindings/nostr-sdk-js/src/protocol/event/builder.rs
- crates/nostr/src/event/builder.rs
- Improve p-tagging in `EventBuilder::comment`
- Avoid unnecessary tagging in `EventBuilder::text_note_reply`
Closes https://github.com/rust-nostr/nostr/issues/653 and https://github.com/rust-nostr/nostr/issues/757
> nostr: improve tagging of replies to text notes

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/protocol/event/kind.rs
- crates/nostr-sdk/examples/status.rs
- crates/nostr/README.md
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/kind.rs
- crates/nostr/src/nips/mod.rs
- crates/nostr/src/nips/nip38.rs
- crates/nostr/src/prelude.rs
Add support for create NIP38 event with `EventBuilder`. Close: https://github.com/rust-nostr/nostr/issues/666
**Usage:**
```rust
// Send a General statuses event to relays
let general = LiveStatus {
status_type: StatusType::General,
expiration: None,
reference: None,
};
let builder = EventBuilder::live_statuses(general, "Building rust-nostr", vec![]);
client.send_event_builder(builder).await?;
// Send a Music statuses event to relays
let music = LiveStatus {
status_type: StatusType::Music,
expiration: Some(Timestamp::now()),
reference: Some("spotify:search:Intergalatic%20-%20Beastie%20Boys".into()),
};
let builder = EventBuilder::live_statuses(music, "Intergalatic - Beastie Boys", vec![]);
client.send_event_builder(builder).await?;
```
None
> NIP38: User Statuses

- crates/nostr-cli/src/cli/parser.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-sdk/src/client/mod.rs
- crates/nostr/src/nips/nip62.rs
Fix warnings produce by `cargo doc --no-deps`
I removed `* clear the [RelayFiltering]` from [`Client::reset`] [because it was removed] 
[`Client::reset`]: https://docs.rs/nostr-sdk/latest/nostr_sdk/client/struct.Client.html#method.reset
[because it was removed]: https://github.com/rust-nostr/nostr/blob/40c20a093672b4cc6d31bb1d96be09c1843d5893/CHANGELOG.md?plain=1#L45
> doc: Fix doc warnings

- CHANGELOG.md
- crates/nostr/src/nips/nip19.rs
- crates/nostr/src/nips/nip21.rs
Change the `Err` type of `ToBech32` to `Infallible` for `SecretKey`, `PublicKey` and `EventId`
They are always less than 1023, so there is no errors.
> nostr: Infallible errors for `nsec`, `npub` and `note` bech32 encoding

- CHANGELOG.md
- bindings/nostr-sdk-ffi/src/relay/options.rs
- bindings/nostr-sdk-js/src/relay/options.rs
- crates/nostr-database/src/collections/events.rs
- crates/nostr-database/src/collections/tree.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-relay-pool/src/relay/options.rs
- crates/nostr-sdk/src/client/mod.rs
- Use `Events::force_insert` when fetching events from relays
- Better handling of auto-closing subscription activity when fetching events
- Add `ReqExitPolicy::WaitForEvents` variant
> pool: improve auto-closing subscriptions and add new exit policy 

- bindings/nostr-sdk-ffi/src/protocol/nips/nip47.rs
- bindings/nostr-sdk-js/src/protocol/nips/nip47.rs
- crates/nostr/src/nips/nip47.rs
Make all `GetInfoResponse` fields optional, except for `methods`.
Ref https://github.com/nostr-protocol/nips/issues/1827
Closes https://github.com/rust-nostr/nostr/issues/795
> nostr: update `GetInfoResponse` fields types

- CHANGELOG.md
- crates/nostr-relay-pool/src/relay/constants.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/options.rs
This PR adds a `notification_channel_size` option to `RelayOptions`, allowing users to set the size of the internal notification sender channel for `InnerRelay`.
I'm not sure if I should also update codes in bindings.
> pool: allow user to set internal notification_channel_size

- CHANGELOG.md
- crates/nostr/src/event/tag/mod.rs
* Add `push`, `pop`, `insert` and `extend` methods to `Tag` struct
Closes https://github.com/rust-nostr/nostr/issues/816
> nostr: extend `Tag` functionality

- CHANGELOG.md
- crates/nostr/src/nips/nip47.rs
Fixes the serialization of a nip47 ResponseResult::ListTransactions. They were missing the transactions object in the result. Including a simple test to serialize and deserialize and make sure it stays the same.
> nostr: fix missing transactions object in serialization of nip47 ListTransactions response

- CHANGELOG.md
- crates/nostr-relay-pool/src/pool/error.rs
- crates/nostr-relay-pool/src/pool/mod.rs
Instead of returning `Error::Failed`, return the `Output` to allow better analysis of the failure causes. Remove `Error::Failed` variant.
Closes https://github.com/rust-nostr/nostr/issues/822
> pool: returns `Output` instead of an error if the message/event sending fails for all relays

- CHANGELOG.md
- crates/nostr-relay-pool/src/policy.rs
- crates/nostr-relay-pool/src/relay/error.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-sdk/examples/blacklist.rs
- crates/nostr-sdk/examples/whitelist.rs
Implemented connection-level admission policies allowing fine-grained control over which relays can connect.
> pool: add connection admission policy

- CHANGELOG.md
- crates/nostr-sdk/examples/code_snippet.rs
- crates/nostr/README.md
- crates/nostr/src/event/builder.rs
- crates/nostr/src/event/kind.rs
- crates/nostr/src/event/tag/kind.rs
- crates/nostr/src/event/tag/standard.rs
- crates/nostr/src/nips/mod.rs
- crates/nostr/src/nips/nipc0.rs
- crates/nostr/src/prelude.rs
[NIP-C0](https://github.com/nostr-protocol/nips/blob/master/C0.md) support. Closes #821 
- `EventBuilder::code_snippet`
- New tag kinds
- dependency (`dep`)
- extension (`extension`)
- license (`license`)
- runtime (`runtime`)
- repository (`repo`)
- New struct `CodeSnippet` a builder struct.
- Example to make a snippet of itself. (Output [notebin.io/nevent1...](https://notebin.io/nevent1qvzqqqq98ypzq8y25sn49pp5vklwrkh7endxsdxs6pwr25pwxtyezrzpkc06lxfyqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hsqgyzdkp6cuvjdfywgmg072xgm4deunc3wvnj2qujxvw36zywwp0fvvte7tzn))
None
> nostr: Add `NIP-C0` (Code Snippets) support

- .gitignore
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- contrib/scripts/check-crates.sh
- contrib/scripts/release.sh
- crates/nostr-mls-storage/Cargo.toml
- crates/nostr-mls-storage/README.md
- crates/nostr-mls-storage/src/groups/error.rs
- crates/nostr-mls-storage/src/groups/mod.rs
- crates/nostr-mls-storage/src/groups/types.rs
- crates/nostr-mls-storage/src/lib.rs
- crates/nostr-mls-storage/src/messages/error.rs
- crates/nostr-mls-storage/src/messages/mod.rs
- crates/nostr-mls-storage/src/messages/types.rs
- crates/nostr-mls-storage/src/welcomes/error.rs
- crates/nostr-mls-storage/src/welcomes/mod.rs
- crates/nostr-mls-storage/src/welcomes/types.rs
- crates/nostr/Cargo.toml
This adds just the nostr-mls-storage crate. This crate provides a storage abstraction layer (traits) and wrapper around the OpenMLS StorageProvider traits.
> Add nostr-mls-storage crate

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- contrib/scripts/check-crates.sh
- contrib/scripts/release.sh
- crates/nostr-mls-memory-storage/Cargo.toml
- crates/nostr-mls-sqlite-storage/Cargo.toml
- crates/nostr-mls-sqlite-storage/README.md
- crates/nostr-mls-sqlite-storage/migrations/V100__initial.sql
- crates/nostr-mls-sqlite-storage/src/db.rs
- crates/nostr-mls-sqlite-storage/src/error.rs
- crates/nostr-mls-sqlite-storage/src/groups.rs
- crates/nostr-mls-sqlite-storage/src/lib.rs
- crates/nostr-mls-sqlite-storage/src/messages.rs
- crates/nostr-mls-sqlite-storage/src/migrations.rs
- crates/nostr-mls-sqlite-storage/src/welcomes.rs
- crates/nostr-mls-storage/Cargo.toml
Adds nostr-mls sqlite storage adpater. 
I've had to return to using my fork of the openmls library. I couldn't figure out a better way to use patch to force the linking of the native sqlite library properly - it doesn't seem to function properly with native libs. 
This includes the commit that changes trait method return signatures.
> Add nostr mls sqlite storage

- crates/nostr-mls-memory-storage/src/groups.rs
- crates/nostr-mls-memory-storage/src/lib.rs
- crates/nostr-mls-sqlite-storage/src/db.rs
- crates/nostr-mls-sqlite-storage/src/groups.rs
- crates/nostr-mls-sqlite-storage/src/messages.rs
- crates/nostr-mls-sqlite-storage/src/welcomes.rs
- crates/nostr-mls-storage/src/groups/mod.rs
- crates/nostr-mls-storage/src/groups/types.rs
- crates/nostr-mls-storage/src/welcomes/types.rs
Use a `BTreeSet` instead of a `Vec` for storing admin public keys and relay URLs.
This ensures unique elements, faster lookups and sorted results.
> mls-storage: replace `Vec` with `BTreeSet` for admins and relays

- Cargo.lock
- crates/nostr-mls-memory-storage/Cargo.toml
- crates/nostr-mls-memory-storage/src/groups.rs
- crates/nostr-mls-memory-storage/src/lib.rs
- crates/nostr-mls-sqlite-storage/Cargo.toml
- crates/nostr-mls-sqlite-storage/src/db.rs
- crates/nostr-mls-sqlite-storage/src/groups.rs
- crates/nostr-mls-sqlite-storage/src/lib.rs
- crates/nostr-mls-sqlite-storage/src/messages.rs
- crates/nostr-mls-sqlite-storage/src/welcomes.rs
- crates/nostr-mls-storage/Cargo.toml
- crates/nostr-mls-storage/src/groups/mod.rs
- crates/nostr-mls-storage/src/groups/types.rs
- crates/nostr-mls-storage/src/messages/types.rs
- crates/nostr-mls-storage/src/welcomes/types.rs
- crates/nostr-mls/src/groups.rs
- crates/nostr-mls/src/messages.rs
- crates/nostr-mls/src/welcomes.rs
- Updates all the mls crates to use `GroupId` values for the mls_group_ids in all types and method signatures.
- Updates all `nostr_group_id` values to use `&[u8; 32]` values instead of a mix of strings and byte arrays.
> Use `GroupId` for `mls_group_ids` and `&[u8; 32]` for `nostr_group_ids`

- crates/nostr-mls-memory-storage/src/lib.rs
- crates/nostr-mls-sqlite-storage/src/db.rs
- crates/nostr-mls-sqlite-storage/src/error.rs
- crates/nostr-mls-sqlite-storage/src/groups.rs
- crates/nostr-mls-sqlite-storage/src/lib.rs
- crates/nostr-mls-storage/src/groups/types.rs
- crates/nostr-mls/examples/mls_memory.rs
- crates/nostr-mls/examples/mls_sqlite.rs
- crates/nostr-mls/src/error.rs
- crates/nostr-mls/src/groups.rs
- crates/nostr-mls/src/key_packages.rs
- crates/nostr-mls/src/messages.rs
- crates/nostr-mls/src/welcomes.rs
This adds and changes several of the public interfaces of the nostr-mls crate. These changes are based on trying to implement this new crate into White Noise and finding places where the interface felt wrong or created more work than necessary for client implementations.
A list of the main changes: 
- Removed the `create_key_package_event` method in favor of just returning the constituent parts and allowing consumers to create the event. This helps avoid async bounds issues.
- Expose the exporter_secret methods so that consumers can directly access those secrets when needed. In White Noise's case, these are used to encrypt media files that are uploaded to blossom servers. 
- Ensure that we create parent directories when creating a new Sqlite database.
- Update a few method params
> More mls methods

- CHANGELOG.md
- crates/nostr-cli/src/main.rs
- crates/nostr-connect/examples/nostr-connect-signer.rs
- crates/nostr-connect/src/client.rs
- crates/nostr-connect/src/signer.rs
- crates/nostr/src/event/builder.rs
- crates/nostr/src/nips/nip46.rs
- Rename the `Message` and `Request` structs to `NostrConnectMessage` and `NostrConnectRequest`
- Rename the `Method` enum to `NostrConnectMethod`
- Add `NostrConnectResponse` struct
- Change types of `NostrConnectMessage` variants
- Required to pass the request method when deserializing the response, to make sure to deserialize the correct type
Closes https://github.com/rust-nostr/nostr/issues/863
> nostr: rework nip46 module

- CHANGELOG.md
- crates/nostr/src/event/tag/kind.rs
A function to simplify creating single-letter tags in uppercase or lowercase
> nostr: add `TagKind::single_letter` method

- CHANGELOG.md
- crates/nostr/src/event/tag/standard.rs
This patch let `TagStandard` parse uppercase `A` and `E` tags.
Before this patch, the following code will not be run, now it run as indeed.
```rust
let root_e_tag = Tag::parse([
"E",
"f29d2b746426e17b8be4c35ba7ce095cde9e04a2b808b4d3c2a32a7a7b0fd22a",
"",
"00000001505e7e48927046e9bbaa728b1f3b511227e2200c578d6e6bb0c77eb9",
]).unwrap();
let root_a_tag = Tag::parse([
"A",
"30617:a008def15796fba9a0d6fab04e8fd57089285d9fd505da5a83fe8aad57a3564d:gitworkshop",
]).unwrap();
assert!(root_e_tag.as_standardized().is_some());
assert!(root_a_tag.as_standardized().is_some());
```
> nostr: Handle uppercase `E` and `A` tags

- crates/nostr-mls/src/key_packages.rs
This removes the protected tag from key package events. It was causing problems with realize accepting it without authentication. The plan is to come back and add this back in the future, once we figure out what's going on with the authentication.
> Remove protected tag temporarily

- CHANGELOG.md
- crates/nostr-relay-builder/src/local/inner.rs
Require the client to auth for publishing NIP-70 protected events.
> relay-builder: add support for NIP-70 protected events

- CHANGELOG.md
- crates/nostr/src/nips/nip22.rs
Fixes the `nip22::extract_root` function by ensuring it properly handles uppercase and
lowercase tags (`k`,`e`,`a`,`i`) when `is_root` is `true`. The issue occurred because `nip22::extract_{kind,event,coordinate,external}` enforced lowercase kinds even for root cases.
N/A
> nostr: fix `nip22::extract_root` to handle uppercase tags when `is_root` is true

- CHANGELOG.md
- crates/nostr-relay-pool/src/relay/status.rs
Fixes https://github.com/rust-nostr/nostr/issues/877
> pool: fix wrong conversion from u8 to RelayStatus

- CHANGELOG.md
- crates/nostr/src/nips/nip22.rs
Closes https://github.com/rust-nostr/nostr/issues/880
> nostr: rename `nip22::Comment` to `nip22::CommentTarget`

- crates/nostr-database/src/collections/events.rs
from "Returns the number of events in the collection." to "Checks if there are no events."
> doc(database): Fix `Events::is_empty` doc

- CHANGELOG.md
- crates/nostr/src/nips/nip10.rs
Remove the `Marker::Mention` variant from NIP-10, according to https://github.com/nostr-protocol/nips/commit/0023ca81 revision.
> nostr: remove `Market::Mention` (NIP-10)

- CHANGELOG.md
- Cargo.lock
- contrib/scripts/check-crates.sh
- crates/nostr/Cargo.toml
- crates/nostr/README.md
- crates/nostr/src/lib.rs
- crates/nostr/src/nips/nip19.rs
- crates/nostr/src/parser.rs
- crates/nostr/src/prelude.rs
Main changes:
- Remove regex dependency
- Remove `parser` feature
- Implement a built-in pattern finder
These changes increase the parsing performance of ~2x and reduce the binary size of (~1.1MB on `x86_64-unknown-linux-gnu` target).
Another advantage is the reduction of the "features" matrix: since the `NostrParser` no longer requires the regex dependency, the `parser` feature is no longer needed.
> nostr: rework `NostrParser`

- CHANGELOG.md
- crates/nostr-relay-pool/src/relay/inner.rs
Send the event notification depending on the `SaveEventStatus` output.
Ref https://github.com/rust-nostr/nostr/issues/909#issuecomment-2938648893
> pool: refine notification sending depending on event database saving status

- CHANGELOG.md
- crates/nostr/src/types/url.rs
Adds a method to retrieve the domain from a `RelayUrl` when applicable.
> nostr: add `RelayUrl::domain` method

- CHANGELOG.md
- crates/nostr-relay-pool/src/relay/constants.rs
- crates/nostr-relay-pool/src/relay/error.rs
- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/mod.rs
- crates/nostr-relay-pool/src/relay/options.rs
- crates/nostr-relay-pool/src/relay/stats.rs
- crates/nostr-relay-pool/src/relay/status.rs
Allow to put on sleep the relays when inactive for some time. Currently this option is disabled by default and must be enabled in the `RelayOptions`. In future PRs will be possible to enable it from the client options (for all relays or just the gossip ones).
- Sleep after configurable timeout (default: 5 min) if conditions are met (i.e., no long-lived subscription active)
- Wake up (reconnect automatically) when interacting with it (send/fetch events, subscribe)
Replaces https://github.com/rust-nostr/nostr/pull/924
Closes https://github.com/rust-nostr/nostr/issues/730
> pool: allow putting relays to sleep when idle

- crates/nostr/src/parser.rs
The `Iterator` implementation of `FindMatches` used recursion. That was causing stack overflow when parsing text of length greater than 5723 without any matches.
Replacing the recursion with while loop allows iterator to work with larger texts and much more efficient, as rust does not optimize tail recursion.
> nostr: Fix recursion with loop in iterator

- CHANGELOG.md
- crates/nostr-sdk/src/gossip/constant.rs
- crates/nostr-sdk/src/gossip/mod.rs
Rework the gossip (NIP-65) relays extraction: extract at max 3 relays per marker (`write`/`read`) from the NIP-65 lists.
It's given the priority to the relays that are both `read` and `write`.
@dluvian
> sdk: extract at max 3 relays per NIP65 marker

- crates/nostr-keyring/CHANGELOG.md
- crates/nostr-keyring/src/lib.rs
Allows crate users to utilize the `Entry` and `Error` types returned by `nostr-keyring` without needing to explicitly add `keyring` as a dependency in `Cargo.toml`
> keyring: Re-export `keyring::Entry` and `keyring::Error`

- crates/nostr-relay-builder/src/local/inner.rs
- crates/nostr/CHANGELOG.md
- crates/nostr/src/filter.rs
- database/nostr-database/src/helper.rs
Add new `MatchEventOptions` struct to control which fields are checked
when matching events against a filter. Modify `Filter::match_event` to
respect these options, skipping checks for disabled fields and enforcing
conditions for enabled ones.
This provides more flexible event matching behavior, allowing callers to
selectively enable/disable specific filter checks as needed.
> Discussed in https://github.com/rust-nostr/nostr/discussions/975
> nostr: flexible filtering with `MatchEventOptions`

- crates/nostr-relay-pool/CHANGELOG.md
- crates/nostr-relay-pool/src/pool/inner.rs
- crates/nostr-relay-pool/src/pool/mod.rs
- crates/nostr-sdk/CHANGELOG.md
- crates/nostr-sdk/src/client/mod.rs
- Update `RelayPool::subscriptions` and `Client::subscriptions` output from `HashMap<SubscriptionId, Filter>` to `HashMap<SubscriptionId, HashMap<RelayUrl, Filter>>`
- Update `RelayPool::subscription` and `Client::subscription` output from `Option<Filter>` to `HashMap<RelayUrl, Filter>`
Previously, only the REQs sent with `Client::subscribe` or `RelayPool::subscribe` (which are sent to ALL relays) were included in the output. This change allows to get all the long-lived subscriptions, including the ones sent only to specific relays (like the gossip ones).
Closes https://github.com/rust-nostr/nostr/issues/814
> pool: update `RelayPool::subscriptions` and `RelayPool::subscription` outputs

- contrib/scripts/check-crates.sh
- contrib/scripts/check-deny.sh
- contrib/scripts/check-docs.sh
- contrib/scripts/check-fmt.sh
- contrib/scripts/check.sh
- contrib/scripts/precommit.sh
- contrib/scripts/release.sh
This works on all distros, unlike the older version (`/bin/bash`), which is
incompatible with some, such as NixOS.
> contrib: Change the shebang from `/bin/bash` to `/usr/bin/env bash`

- crates/nostr-relay-pool/src/relay/inner.rs
- crates/nostr-relay-pool/src/relay/options.rs
- crates/nostr/src/event/mod.rs
- crates/nostr/src/nips/nip06/bip32.rs
- crates/nostr/src/nips/nip44/v2.rs
- crates/nostr/src/util/hex.rs
Ran `cargo +stable clippy` and addressed its warnings.  
One lint remains unresolved regarding boxing the `RelayMessage` variant in `RelayNotification::Message`, as it exceeds 248 bytes in size. Refer to the [Clippy documentation](https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant) for details. Let me know if this should be fixed, as it would introduce a breaking change.
> Fix simple warning lints

- crates/nwc/CHANGELOG.md
- crates/nwc/examples/nwc.rs
- crates/nwc/src/lib.rs
- crates/nwc/src/options.rs
The only way to get the status of the relays in the `NWC` is the `status` function. With the recent addition of `Monitor` it would be convenient to add it (I thought in `NostrWalletConnectOptions`).
> Add Monitor to NostrWalletConnectOptions

- crates/nostr-relay-pool/CHANGELOG.md
- crates/nostr-relay-pool/src/relay/constants.rs
- crates/nostr-relay-pool/src/relay/limits.rs
By default, enable only the max message size limit (5MB) and keep the max event size limit disabled (previously 70kb).
This will prevent issues with NWC or similar protocols, which may often receive events above 70kb.
> relay-pool: disable the default event max size limit

- Cargo.lock
- Cargo.toml
- README.md
- contrib/scripts/check-crates.sh
- contrib/scripts/release.sh
- signer/nostr-browser-signer-proxy/CHANGELOG.md
- signer/nostr-browser-signer-proxy/Cargo.toml
- signer/nostr-browser-signer-proxy/README.md
- signer/nostr-browser-signer-proxy/examples/browser-signer-proxy.rs
- signer/nostr-browser-signer-proxy/index.html
- signer/nostr-browser-signer-proxy/proxy.js
- signer/nostr-browser-signer-proxy/src/error.rs
- signer/nostr-browser-signer-proxy/src/lib.rs
- signer/nostr-browser-signer-proxy/src/prelude.rs
- signer/nostr-browser-signer-proxy/style.css
Add `nostr-browser-signer-proxy` crate, to allow using NIP-07 signer in native applications.
> Add browser signer (NIP-07) proxy

- database/nostr-lmdb/CHANGELOG.md
- database/nostr-lmdb/src/lib.rs
- database/nostr-lmdb/src/store/lmdb/mod.rs
- database/nostr-lmdb/src/store/mod.rs
Add max_readers and additional_dbs configuration options to NostrLmdbBuilder to allow fine-tuning of LMDB environment settings.
- **max_readers**: Controls the maximum number of reader threads (defaults to 126)
- **additional_dbs**: Specifies additional database slots beyond the 9 internal ones (defaults to 0)
This addresses part of the feedback from PR #992 where the reviewer suggested changing the parameter name to `additional_dbs` since 9 databases are already defined internally.
- Following the same pattern as the existing `map_size` field
- All parameters cascade through: NostrLmdbBuilder → Store → Lmdb
- Uses sensible defaults (126 for max_readers, 0 for additional_dbs)
- No breaking changes - all existing code continues to work
> lmdb: add max_readers and additional_dbs fields to NostrLmdbBuilder

- crates/nostr-relay-pool/CHANGELOG.md
- crates/nostr-relay-pool/src/transport/websocket.rs
Add the `TransportSink` struct as a replacement for the `sink_map_err` method that was causing panics in case of connection interruption (i.e., broken pipe error).
Fixes https://github.com/rust-nostr/nostr/issues/984
Replaces #987
> relay-pool: add TransportSink for WebSocket

- crates/nostr-relay-pool/CHANGELOG.md
- crates/nostr-relay-pool/src/relay/inner.rs
Fixes: #1022
`RelayOptions::ban_relay_on_mismatch` doesn't depends on `RelayOptions::verify_subscriptions` anymore, the events will be checked if one of them is enabled.
> relay-pool: fix `ban_relay_on_mismatch` requiring `verify_subscriptions` in `RelayOptions`

- signer/nostr-browser-signer-proxy/CHANGELOG.md
- signer/nostr-browser-signer-proxy/examples/browser-signer-proxy.rs
- signer/nostr-browser-signer-proxy/src/lib.rs
A function that returns `true` if the user is connected to the server and `false` if not
> browser-signer-proxy: `BrowserSignerProxy::is_session_active` to return whether the session is active or not

- crates/nostr-sdk/CHANGELOG.md
- crates/nostr-sdk/src/client/mod.rs
`Client::public_key` function to retrieve the public key
> sdk: `Client::public_key` function to retrieve the public key

- crates/nostr/CHANGELOG.md
- crates/nostr/src/nips/nip22.rs
Add a check to verify that `a`/`A` and `k`/`K` tags have the same event kind.
Closes https://github.com/rust-nostr/nostr/issues/1031
> nostr: deprecate `kind` field in `CommentTarget::Coordinate` variant

- crates/nostr/CHANGELOG.md
- crates/nostr/src/event/tag/standard.rs
- crates/nostr/src/nips/nip73.rs
- Add `nips::nip73::Nip73Kind`
- Add `TagStandard::Nip73Kind`
- Support `Nip37Kind` in `TagStandard::to_vec`
- Support `Nip37Kind` in `TagStandard::parse`
- Unit tests for `Nip37Kind` and `Kind`
`TagStandard::parse` wasn't parsing `Kind`, I fix it as a minor fix (Should I add it to the changelog?)
> nostr: Support NIP-73 kind

- crates/nostr/CHANGELOG.md
- crates/nostr/src/event/tag/kind.rs
- crates/nostr/src/event/tag/mod.rs
- crates/nostr/src/event/tag/standard.rs
- Add `TagKind::Head`
- Add `Tag::head` function
- Add `TagStandard::GitHead`
- Support `TagStandard::GitHead` in `TagStandard::to_vec`
- Support `TagStandard::GitHead` in `TagStandard::parse`
none
> nostr: Add `HEAD` tag kind

- mls/nostr-mls/src/error.rs
- mls/nostr-mls/src/groups.rs
- mls/nostr-mls/src/lib.rs
As per [RFC9420](https://datatracker.ietf.org/doc/rfc9420/) group context should be common to all members(leaf nodes).
When creating group, RequiredCapabilitiesExtensions should be provided. This allows group contexts to be updated in future epochs.
> mls: Fix group context updates

- crates/nostr-sdk/examples/comment.rs
- crates/nostr/CHANGELOG.md
- crates/nostr/src/event/builder.rs
Change the `EventBuilder::comment` function `root` and `comment_to` parameters types from `&Event` to `CommentTarget<'_>` 
- Makes the API more flexible by allowing comments on any target, not just `Event`
- Enables replying to events without requiring a signed event
> refactor(nostr): change `EventBuilder::comment` parameters to `CommentTarget<'_>`

- README.md
The readme was missing the following NIPs (which are part of the official [NIP repository](https://github.com/nostr-protocol/nips)):
- 8 - Handling Mentions
- 64 - Chess (PGN)
- 68 - Picture-first feeds
- 87 - Ecash Mint Discoverability
I assume these are not implemented, otherwise they would have already been in the readme. But if one or more of these is implemented already, we can just change the ❌ to ✅
Note that I did not add [NIP-EE](https://github.com/nostr-protocol/nips/blob/master/EE.md) since it is supported here but only using the MLS crate so I wasn't sure if I should add it.
> Add missing NIPs to readme

- crates/nostr/CHANGELOG.md
- crates/nostr/src/types/url.rs
A function to return the relay host
> nostr: `RelayUrl::host` function
