crates/nostr/src/nips/nip05.rs
Add ability to get public key from nip-05
=> Add ability to get public key from nip-05

crates/nostr/Cargo.toml, crates/nostr/examples/nip65.rs, crates/nostr/src/event/kind.rs, crates/nostr/src/event/tag.rs, crates/nostr/src/nips/mod.rs, crates/nostr/src/nips/nip65.rs
Add support for event kind 10002 (Relay List Metadata) from NIP-65.
n/a
Add support for NIP-65 Relay List Metadata
=> Add support for Relay List Metadata (NIP-65)

crates/nostr/src/message/client.rs
Should make it simpler to use `ClientMessage`
=> Impl Serialize and Deserialize for ClientMessage

crates/nostr/src/message/relay.rs
Same as #47 but for `RelayMessage`
=> Impl Serialize and Deserialize for RelayMessage

crates/nostr/Cargo.toml, crates/nostr/src/event/mod.rs
Add NIP-03: OpenTimestamps proof for events
The used crate `nostr-ots`, which I created yesterday, it is not been thoroughly tested yet, so this can wait a bit
UPDATE: `nostr-ots` has been reviewed so this is ready to be reviewed
=> Add NIP-03: OpenTimestamps proof for events

crates/nostr/src/event/tag.rs
Add additional tags for NIP57 support (#68)
Initially I used and `Event` type for the `description` tag as its should be a valid zap request event. However, there is a sha256 check that can fail if the order of values is changed during serialization and deserialization so it is now a string and its up to the user to make sure it is valid.
Added
- `description` tag
- `preimage` tag
- `amount`  tag
- `bolt11` tag
- `relays` tag
=> Nip 57 Tag Kinds

crates/nostr-sdk/src/client/blocking.rs
NIP46 remote signer for blocking client
Add
- `with_remote_signer` to blocking `Client`
- `with_remote_signer_and_opts` to blocking `Client`
=> Blocking `with_remote_signer`

crates/nostr/src/nips/nip46.rs
Currently the Delegate response returns only the unsigned delegation string in the NIP46 response, This is not enough for the app to create a delegation tag as it needs the signature.  This modifies the response to include the additional information required for delegation over nostr connect.
https://github.com/nostr-protocol/nips/blob/3cec80d99ebbee6b72aae31f1856181d04971244/46.md?plain=1#L81
Side note: By my reading NIP26 calls the signature of the hash of the unsigned string the delegation token, whereas in this crate the delegation token is the unsigned string. 
https://github.com/nostr-protocol/nips/blob/3cec80d99ebbee6b72aae31f1856181d04971244/26.md?plain=1#L74
> The delegator (8e0d3d3e) then signs a SHA256 hash of the above delegation string, the result of which is the delegation …
=> NIP46 delegation response

crates/nostr/src/event/mod.rs
This adds some preliminary support for NIP-40 Expiration Timestamp.
Feel free to comment on what else could be added for this NIP.
NIP40: add `is_expired` method to events with Expiration Timestamp tags
=> Add support for handling  NIP-40 Expiration Timestamp

crates/nostr/src/event/builder.rs
Changes the `new_zap` preimage parameter from mandatory to optional to ensure that we follow the [NIP-57 specification](https://github.com/nostr-protocol/nips/blob/master/57.md#appendix-e-zap-receipt-event) properly. 
Also adds two new tests to test that the function works fine both with or without the preimage.
```md
- Make preimage parameter in the EventBuilder::new_zap function optional
```
=> Make preimage optional in zap event builder

crates/nostr/src/event/tag.rs, crates/nostr/src/nips/mod.rs, crates/nostr/src/nips/nip58.rs
This PR adds support to easily create / award badges as defined in NIP-58.
Closes https://github.com/encointer/personhood-oracle/issues/8.
=> Add support for NIP-58 Badges

crates/nostr/src/event/tag.rs
Implements parsing of NIP-39 external identities from tags and adds an Identity struct to make working with it easier.
Nothing in this PR actually validates the identities. I wasn't sure if that was something that was wanted directly in this library. Also I believe this will actually affect anyone using `Tag::Generic` currently to work with these tags.
NIP-39 tag parsing
=> implement nip-39 external identity tag parsing

crates/nostr-sdk/src/relay/pool.rs
=> sdk: improve `send_msg` method

crates/nostr/src/key/mod.rs
=> fix: `from_pk_str` error typo

crates/nostr/src/nips/nip47.rs
Implements this https://github.com/nostr-protocol/nips/pull/685
=> Add new functions to NWC

bindings/nostr-ffi/src/event/tag.rs, bindings/nostr-ffi/src/nostr.udl, bindings/nostr-sdk-ffi/src/nostr_sdk.udl, crates/nostr/README.md, crates/nostr/src/event/tag.rs, crates/nostr/src/nips/mod.rs, crates/nostr/src/nips/nip48.rs, crates/nostr/src/prelude.rs
=> nostr: add support to NIP48

crates/nostr-sdk/src/client/blocking.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr-sdk/src/client/options.rs, crates/nostr-sdk/src/relay/options.rs, crates/nostr/src/message/relay.rs, crates/nostr/src/nips/nip47.rs, crates/nostr/src/nips/nip58.rs
Fixed some links in the rustdoc documentation for `nostr` and `nostr-sdk`.
=> fix rustdoc links in documentation

bindings/nostr-ffi/src/message/relay.rs, crates/nostr/src/message/relay/mod.rs, crates/nostr/src/message/relay/raw.rs
PR to resolve #205. Let me know if I should squash the commits
=> Implement `CLOSED` messages

bindings/nostr-ffi/src/event/tag.rs, crates/nostr-database/examples/indexes.rs, crates/nostr-database/examples/memory.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr/src/event/builder.rs, crates/nostr/src/event/mod.rs, crates/nostr/src/event/tag/mod.rs, crates/nostr/src/message/subscription.rs, crates/nostr/src/nips/nip58.rs
Remove `Tag::PubKey` and `Tag::ContactList`
=> nostr: add `Tag::PublicKey`

bindings/nostr-ffi/src/key/mod.rs, bindings/nostr-ffi/src/key/public_key.rs, bindings/nostr-ffi/src/key/secret_key.rs
Add `Keys::sign_schnorr` and removed not needed `Arc`
=> ffi: add `Keys::sign_schnorr`

crates/nostr/src/nips/nip19.rs
This adds optional author parsing from nevents as specified by NIP19.
We still need `kind` as well which I have a future patch for, but `nak` does not currently have a way to create these so I don't have a way to generate test data for it
```
TLV 2: author
for naddr, the 32 bytes of the pubkey of the event
*for nevent, optionally, the 32 bytes of the pubkey of the event*
```
=> nip19: add nevent author

bindings/nostr-ffi/src/error.rs, bindings/nostr-ffi/src/message/client.rs, bindings/nostr-ffi/src/message/relay.rs, bindings/nostr-ffi/src/message/subscription.rs
=> ffi(nostr): complete message module

bindings/nostr-ffi/src/lib.rs, bindings/nostr-ffi/src/types/contact.rs, bindings/nostr-ffi/src/types/image.rs, bindings/nostr-ffi/src/types/metadata.rs, bindings/nostr-ffi/src/types/time.rs, bindings/nostr-sdk-ffi/src/relay.rs
=> ffi(nostr): complete types module

crates/nostr-sqlite/README.md
=> Fix typo in README.md

bindings/nostr-ffi/src/event/tag.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr/src/event/builder.rs, crates/nostr/src/event/tag/mod.rs
Implements https://github.com/nostr-protocol/nips/pull/954
=> Add uppercase P tag to Zaps

bindings/nostr-ffi/src/error.rs, bindings/nostr-ffi/src/event/mod.rs, bindings/nostr-ffi/src/nips/mod.rs, bindings/nostr-ffi/src/nips/nip01.rs, bindings/nostr-ffi/src/nips/nip11.rs, bindings/nostr-ffi/src/nips/nip13.rs, bindings/nostr-ffi/src/nips/nip19.rs, bindings/nostr-ffi/src/nips/nip21.rs, bindings/nostr-ffi/src/nips/nip26.rs, bindings/nostr-ffi/src/nips/nip47.rs, bindings/nostr-ffi/src/nips/nip65.rs, bindings/nostr-ffi/src/nips/nip98.rs, bindings/nostr-ffi/src/util.rs, crates/nostr/src/nips/nip13.rs, crates/nostr/src/nips/nip19.rs, crates/nostr/src/nips/nip21.rs, crates/nostr/src/nips/nip47.rs, crates/nostr/src/nips/nip58.rs
=> ffi(nostr): complete nips module

bindings/nostr-ffi/src/nips/nip11.rs, crates/nostr-database/README.md, crates/nostr-database/src/flatbuffers/mod.rs, crates/nostr-database/src/index.rs, crates/nostr-indexeddb/examples/webapp/README.md, crates/nostr/src/nips/nip11.rs, crates/nostr/src/nips/nip44/mod.rs, crates/nostr/src/nips/nip47.rs, crates/nostr/src/nips/nip57.rs
This fixes some misspelled words.
=> Fix some typos

crates/nostr/src/nips/nip94.rs
Adds a `TryFrom` implementation for `FileMetadata` from vector of `Tag`s
=> add try_from implementation for filemetadata from tags vector

crates/nostr/src/event/unsigned.rs
copy-pasted from normal events
=> Verify unsigned event ids

bindings/nostr-ffi/src/event/tag.rs, crates/nostr/src/event/tag.rs
These are used to identify if the params are encrypted in [NIP 90](https://github.com/nostr-protocol/nips/blob/master/90.md)
=> Add encrypted tag kind

crates/nostr-database/src/index.rs, crates/nostr/src/message/subscription.rs
=> nostr: not skip serialization of empty lists in `Filter`

crates/nostr/src/nips/nip47.rs
=> Dervice more traits for NWC errors

bindings/nostr-ffi/src/message/relay.rs, bindings/nostr-sdk-ffi/src/client/mod.rs, book/snippets/nostr/js/index.js, book/snippets/nostr/js/src/messages/relay.js, book/snippets/nostr/rust/src/event/builder.rs, book/snippets/nostr/rust/src/main.rs, book/snippets/nostr/rust/src/messages/mod.rs, book/snippets/nostr/rust/src/messages/relay.rs, book/src/nostr/05_02-relay-message.md
Add `from_json` and `as_json` to `RelayMessage`
Closes #316
=> ffi(nostr): convert `RelayMessage` to `Object` and add `RelayMessageEnum`

bindings/nostr-ffi/src/lib.rs, bindings/nostr-ffi/src/message/client.rs, bindings/nostr-ffi/src/message/mod.rs, bindings/nostr-sdk-ffi/src/client/mod.rs, bindings/nostr-sdk-ffi/src/relay/mod.rs
=> ffi(nostr): convert `ClientMessage` to `Object` and add `ClientMessageEnum`

bindings/nostr-ffi/src/event/builder.rs, bindings/nostr-ffi/src/event/id.rs, bindings/nostr-ffi/src/event/kind.rs, bindings/nostr-ffi/src/event/mod.rs, bindings/nostr-ffi/src/event/tag.rs, bindings/nostr-ffi/src/lib.rs, bindings/nostr-ffi/src/message/subscription.rs, bindings/nostr-ffi/src/nips/nip01.rs, bindings/nostr-ffi/src/nips/nip26.rs
=> ffi(nostr): add `Kind` and `KindEnum`

bindings/nostr-ffi/src/event/mod.rs, bindings/nostr-ffi/src/event/raw.rs
Similar to #335, this is useful for app developers so parsing and modeling is no longer needed on each platform.
* [ ✅] I followed the [contribution guidelines](https://github.com/rust-nostr/nostr/blob/master/CONTRIBUTING.md)
* [✅ ] I ran `make precommit` before committing
* [✅ ] I've added docs for the new feature
=> add serialization and deserialization for RawEvent in nostr-ffi

crates/nostr/src/nips/nip47.rs
Context: https://github.com/damus-io/damus/issues/1954#issuecomment-1986940399
=> Remove trailing slash from relay in NWC uri

bindings/nostr-sdk-ffi/bindings-python/examples/limits.py, bindings/nostr-sdk-ffi/src/client/mod.rs, bindings/nostr-sdk-ffi/src/client/options.rs, bindings/nostr-sdk-ffi/src/relay/limits.rs, bindings/nostr-sdk-ffi/src/relay/mod.rs, bindings/nostr-sdk-ffi/src/relay/options.rs, bindings/nostr-sdk-js/src/client/mod.rs, bindings/nostr-sdk-js/src/client/options.rs, bindings/nostr-sdk-js/src/relay/limits.rs, bindings/nostr-sdk-js/src/relay/mod.rs, crates/nostr-relay-pool/src/lib.rs, crates/nostr-relay-pool/src/pool/internal.rs, crates/nostr-relay-pool/src/relay/internal.rs, crates/nostr-relay-pool/src/relay/limits.rs, crates/nostr-relay-pool/src/relay/mod.rs, crates/nostr-relay-pool/src/relay/options.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr-sdk/src/client/options.rs
=> Allow to edit `RelayLimits`

bindings/nostr-sdk-ffi/bindings-python/examples/custom-database.py, bindings/nostr-sdk-ffi/src/database/custom.rs, bindings/nostr-sdk-ffi/src/database/mod.rs
* Add `CustomNostrDatabase` trait
* Add `NostrDatabase::custom`
* Add `custom-database.py` example
Closes https://github.com/rust-nostr/nostr/issues/325
=> ffi(sdk): allow to use custom database

.gitignore, bindings/nostr-ffi/src/event/mod.rs, bindings/nostr-ffi/src/event/tag.rs, bindings/nostr-ffi/src/message/subscription.rs, bindings/nostr-ffi/src/nips/nip01.rs, bindings/nostr-js/src/message/subscription.rs, crates/nostr-database/src/index.rs, crates/nostr-database/src/lib.rs, crates/nostr-database/src/tag_indexes.rs, crates/nostr/src/event/builder.rs, crates/nostr/src/event/mod.rs, crates/nostr/src/event/tag.rs, crates/nostr/src/message/subscription.rs, crates/nostr/src/nips/nip01.rs, crates/nostr/src/nips/nip26.rs, crates/nostr/src/nips/nip46.rs, crates/nostr/src/nips/nip47.rs, crates/nostr/src/nips/nip94.rs, crates/nostr/src/util/hex.rs
Re-add support to `Filter::match_event` with an improvement to performance
=> Re-add support to `Filter::match_event`

bindings/nostr-ffi/src/types/metadata.rs
This is for metadata model creation used in bindings.
* [✅ ] I followed the [contribution guidelines](https://github.com/rust-nostr/nostr/blob/master/CONTRIBUTING.md)
* [✅ ] I ran `make precommit` before committing
* [✅ ] I've added docs for the new feature
=> add MetadataRecord for Metadata in nostr-ffi

bindings/nostr-ffi/src/event/id.rs, bindings/nostr-sdk-ffi/src/lib.rs, bindings/nostr-sdk-ffi/src/negentropy.rs, bindings/nostr-sdk-ffi/src/pool/mod.rs, bindings/nostr-sdk-ffi/src/relay/mod.rs
* Add `NegentropyItem`
* Fix swift bindings compilation
Fixes https://github.com/rust-nostr/nostr/issues/360
=> ffi(sdk): replace `HashMap<Arc<EventId>, Arc<Timestamp>>` with `Vec<NegentropyItem>`

crates/nostr/src/key/vanity.rs
Implemented a new function 'check_prefix_chars()' in the 'Keys' implementation to enhance validation of prefix characters for vanity keys. This function is utilised to validate both hexadecimal and bech32 characters, improving code reusability and readability. This change reduces duplication and streamlines the 'vanity()' function.
=> Refactor prefix character validation in vanity keys

bindings/nostr-ffi/src/event/builder.rs, bindings/nostr-ffi/src/event/kind.rs, bindings/nostr-ffi/src/event/tag.rs, bindings/nostr-js/src/event/builder.rs, crates/nostr/README.md, crates/nostr/src/event/builder.rs, crates/nostr/src/event/kind.rs, crates/nostr/src/event/tag.rs
Close https://github.com/rust-nostr/nostr/issues/331
Add NIP32 support
=> Add NIP32 support

.gitignore, CHANGELOG.md, Cargo.lock, README.md, bindings/nostr-sdk-ffi/Cargo.toml, bindings/nostr-sdk-ffi/bindings-python/examples/database.py, bindings/nostr-sdk-ffi/src/database/mod.rs, contrib/scripts/check-crates.sh, crates/nostr-ndb/Cargo.toml, crates/nostr-ndb/README.md, crates/nostr-ndb/src/lib.rs, crates/nostr-sdk/Cargo.toml, crates/nostr-sdk/README.md, crates/nostr-sdk/examples/nostrdb.rs, crates/nostr-sdk/src/lib.rs
Add [ndb](https://github.com/damus-io/nostrdb) storage backend
Waiting for:
* https://github.com/damus-io/nostrdb-rs/issues/2
* https://github.com/damus-io/nostrdb-rs/issues/5
* https://github.com/damus-io/nostrdb-rs/pull/4
=> Add `nostr-ndb` storage backend

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, bindings/nostr-sdk-ffi/Cargo.toml, bindings/nostr-sdk-ffi/bindings-python/examples/client-with-opts.py, bindings/nostr-sdk-ffi/bindings-python/examples/tor.py, bindings/nostr-sdk-ffi/src/client/options.rs, bindings/nostr-sdk-ffi/src/nwc/options.rs, bindings/nostr-sdk-ffi/src/relay/mod.rs, bindings/nostr-sdk-ffi/src/relay/options.rs, contrib/scripts/check-crates.sh, crates/nostr-relay-pool/Cargo.toml, crates/nostr-relay-pool/README.md, crates/nostr-relay-pool/src/lib.rs, crates/nostr-relay-pool/src/relay/internal.rs, crates/nostr-relay-pool/src/relay/mod.rs, crates/nostr-relay-pool/src/relay/options.rs, crates/nostr-sdk/Cargo.toml, crates/nostr-sdk/README.md, crates/nostr-sdk/examples/bot.rs, crates/nostr-sdk/examples/client-with-opts.rs, crates/nostr-sdk/examples/tor.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr-sdk/src/client/options.rs, crates/nwc/Cargo.toml, crates/nwc/src/options.rs
* https://github.com/snapview/tungstenite-rs/pull/431
=> sdk: add support to embedded tor client

CHANGELOG.md, Cargo.lock, Cargo.toml, bindings/nostr-sdk-ffi/Cargo.toml, bindings/nostr-sdk-ffi/bindings-python/examples/mock_relay.py, bindings/nostr-sdk-ffi/bindings-python/examples/relays.py, bindings/nostr-sdk-ffi/src/error.rs, bindings/nostr-sdk-ffi/src/lib.rs, bindings/nostr-sdk-ffi/src/mock.rs, contrib/scripts/check-crates.sh, contrib/scripts/release.sh, crates/nostr-relay-builder/Cargo.toml, crates/nostr-relay-builder/README.md, crates/nostr-relay-builder/examples/mock.rs, crates/nostr-relay-builder/src/lib.rs, crates/nostr-relay-builder/src/mock.rs, crates/nostr-relay-builder/src/prelude.rs, crates/nostr-relay-pool/Cargo.toml, crates/nostr-relay-pool/src/relay/mod.rs
Closes https://github.com/rust-nostr/nostr/issues/524
=> Add `MockRelay`

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, bindings/nostr-sdk-ffi/Cargo.toml, bindings/nostr-sdk-ffi/bindings-python/scripts/generate-windows.sh, bindings/nostr-sdk-ffi/src/database/mod.rs, contrib/scripts/check-crates.sh, crates/nostr-cli/Cargo.toml, crates/nostr-cli/src/main.rs, crates/nostr-database/README.md, crates/nostr-database/src/flatbuffers/event_generated.rs, crates/nostr-database/src/flatbuffers/mod.rs, crates/nostr-lmdb/Cargo.toml, crates/nostr-lmdb/README.md, crates/nostr-lmdb/src/lib.rs, crates/nostr-lmdb/src/store/error.rs, crates/nostr-lmdb/src/store/lmdb/index.rs, crates/nostr-lmdb/src/store/lmdb/mod.rs, crates/nostr-lmdb/src/store/mod.rs, crates/nostr-lmdb/src/store/types/event.rs, crates/nostr-lmdb/src/store/types/filter.rs, crates/nostr-lmdb/src/store/types/mod.rs, crates/nostr-sdk/Cargo.toml, crates/nostr-sdk/README.md, crates/nostr-sdk/examples/lmdb.rs, crates/nostr-sdk/src/lib.rs, crates/nostr-sqlite/README.md, crates/nostr-sqlite/src/lib.rs
* Add LMDB storage backend
* Deprecate SQLite storage backend
=> Add LMDB storage backend

CHANGELOG.md, bindings/nostr-ffi/src/event/tag.rs, bindings/nostr-ffi/tests/test_to_string.py
Closes https://github.com/rust-nostr/nostr/issues/577
=> ffi(nostr): add `tag_kind_to_string` func

CHANGELOG.md, bindings/nostr-sdk-ffi/src/protocol/event/tag/standard.rs, bindings/nostr-sdk-ffi/src/protocol/nips/nip34.rs, bindings/nostr-sdk-ffi/src/protocol/nips/nip53.rs, bindings/nostr-sdk-ffi/src/protocol/nips/nip57.rs, bindings/nostr-sdk-js/src/protocol/nips/nip34.rs, bindings/nostr-sdk-js/src/protocol/nips/nip57.rs, crates/nostr/examples/nip57.rs, crates/nostr/src/event/builder.rs, crates/nostr/src/event/tag/standard.rs, crates/nostr/src/nips/nip34.rs, crates/nostr/src/nips/nip53.rs, crates/nostr/src/nips/nip57.rs
Change `TagStandard::Relays` variant inner value from `Vec<Url>` to `Vec<RelayUrl>`.
=> nostr: change `TagStandard::Relays` variant inner value

crates/nostr-connect/README.md
A description for `nostr-connect` crate
=> connect: Readme description

bindings/nostr-sdk-ffi/src/client/mod.rs, bindings/nostr-sdk-ffi/src/relay/mod.rs, bindings/nostr-sdk-js/src/client/mod.rs, bindings/nostr-sdk-js/src/relay/mod.rs, crates/nostr-relay-pool/src/pool/mod.rs, crates/nostr-relay-pool/src/relay/mod.rs, crates/nostr-relay-pool/src/relay/status.rs, crates/nostr-sdk/src/client/mod.rs
Closes https://github.com/rust-nostr/nostr/issues/799
@mikedilger
=> doc: improve connection docs

CHANGELOG.md, Cargo.lock, contrib/scripts/check-crates.sh, crates/nostr/Cargo.toml, crates/nostr/README.md, crates/nostr/examples/parser.rs, crates/nostr/src/lib.rs, crates/nostr/src/nips/nip21.rs, crates/nostr/src/parser.rs, crates/nostr/src/prelude.rs
Add `NostrParser` struct, to handle parsing text containing URLs, nostr URIs, hashtags and line breaks. 
```toml
[dependencies]
nostr = { git = "...", rev = "...", features = ["parser"] }
```
```rust
use nostr::prelude::*;
fn main() -> Result<()> {
let parser = NostrParser::new();
let text: &str = "I have never been very active in discussions but working on rust-nostr (at the time called nostr-rs-sdk) since September 2022 🦀 \n\nIf I remember correctly there were also nostr:nprofile1qqsqfyvdlsmvj0nakmxq6c8n0c2j9uwrddjd8a95ynzn9479jhlth3gpvemhxue69uhkv6tvw3jhytnwdaehgu3wwa5kuef0dec82c33w94xwcmdd3cxketedsux6ertwecrgues0pk8xdrew33h27pkd4unvvpkw3nkv7pe0p68gat58ycrw6ps0fenwdnvva48w0mzwfhkzerrv9ehg0t5wf6k2qgnwaehxw309ac82unsd3jhqct89ejhxtcpz4mhxue69uhhyetvv9ujuerpd46hxtnfduhsh8njvk and …
```
=> nostr: add `NostrParser`

CHANGELOG.md, crates/nostr/src/nips/nip47.rs
Nip-47 Notifications are not yet supported by this project and i want them.
I just copy paste :)
=> nostr: add nip47::Notification

Cargo.lock, README.md, contrib/scripts/check-crates.sh, contrib/scripts/release.sh, crates/nostr-keyring/Cargo.toml, crates/nostr-keyring/README.md, crates/nostr-keyring/examples/async.rs, crates/nostr-keyring/examples/blocking.rs, crates/nostr-keyring/src/lib.rs, crates/nostr-keyring/src/prelude.rs
Closes https://github.com/rust-nostr/nostr/issues/392
=> Add nostr-keyring

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, contrib/scripts/check-crates.sh, contrib/scripts/release.sh, crates/nostr-mls-memory-storage/Cargo.toml, crates/nostr-mls-memory-storage/README.md, crates/nostr-mls-memory-storage/src/groups.rs, crates/nostr-mls-memory-storage/src/lib.rs, crates/nostr-mls-memory-storage/src/messages.rs, crates/nostr-mls-memory-storage/src/welcomes.rs
This adds an in-memory implementation of the `NostrMlsStorageProvider` traits.
=> Add nostr-mls-memory-storage crate

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/nostr-relay-pool/Cargo.toml, crates/nostr-relay-pool/src/relay/error.rs, crates/nostr-relay-pool/src/relay/inner.rs, crates/nostr-relay-pool/src/relay/mod.rs
Closes https://github.com/rust-nostr/nostr/issues/848
=> pool: drop support for deprecated negentropy protocol

crates/nostr-mls-sqlite-storage/src/groups.rs, crates/nostr-mls/src/error.rs, crates/nostr-mls/src/groups.rs, crates/nostr-mls/src/messages.rs, crates/nostr-mls/src/welcomes.rs
This is a collection of small bug fixes
- Fixes a bug in nostr_mls where we weren't creating group relays when groups are created (either by creation or by processing of welcome messages)
- Add better error for missing processed welcomes
- Update last_message_at and last_message_id for groups when processing/creating messages
=> Small bug fixes

CHANGELOG.md, crates/nostr/src/event/builder.rs
Closes https://github.com/rust-nostr/nostr/issues/861
=> Encrypt NIP-46 events with NIP-44 instead of NIP-04

CHANGELOG.md, README.md, crates/nostr/src/event/builder.rs, crates/nostr/src/event/kind.rs, crates/nostr/src/event/tag/error.rs, crates/nostr/src/event/tag/kind.rs, crates/nostr/src/event/tag/standard.rs, crates/nostr/src/nips/mod.rs, crates/nostr/src/nips/nip88.rs, crates/nostr/src/prelude.rs
Closes https://github.com/rust-nostr/nostr/issues/887
=> nostr: add NIP-88 support

CHANGELOG.md, crates/nostr-relay-pool/src/relay/inner.rs, crates/nostr/examples/nip11.rs, crates/nostr/src/nips/nip11.rs
Update `RelayInformationDocument::get` signature.
=> nostr: add `Nip11GetOptions`

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, crates/nostr-keyring/Cargo.toml
Closes https://github.com/rust-nostr/nostr/issues/941
=> keyring: fix keys persistence between OS restarts on Linux

mls/nostr-mls/src/lib.rs, mls/nostr-mls/src/messages.rs, mls/nostr-mls/src/util.rs
Fixes https://github.com/rust-nostr/nostr/issues/967
=> mls: fix msg decryption error due to missing exporter secret

crates/nostr-relay-pool/src/pool/mod.rs, crates/nostr-sdk/src/client/mod.rs, crates/nostr/src/nips/nip46.rs
Fixing unresolved links in the docs
=> doc: Fix unresolved links

crates/nostr-relay-pool/CHANGELOG.md, crates/nostr-relay-pool/src/relay/inner.rs, crates/nostr-relay-pool/src/relay/mod.rs, crates/nostr-relay-pool/src/relay/options.rs
Follow-up of 71b4fd7b9e0990630f64c0582d7cd24c4ed66f2f
=> relay-pool: add `RelayOptions::verify_subscriptions` option

crates/nostr/src/event/tag/standard.rs
Closes https://github.com/rust-nostr/nostr/issues/1033
=> nostr: add `TagStandard::QuoteAddress` variant

README.md, crates/nostr/CHANGELOG.md, crates/nostr/src/event/builder.rs, crates/nostr/src/event/kind.rs
Resolve #1027 by support NIP-A0 (Voice Messages)
- Add `Kind::VoiceMessage` (1222)
- Add `Kind::VoiceMessageReply` (1244)
- Add `EventBuilder::voice_message`
- Add `EventBuilder::voice_message_reply`
The NIP: <https://github.com/nostr-protocol/nips/blob/master/A0.md>
=> nostr: Support NIP-A0

database/nostr-lmdb/CHANGELOG.md, database/nostr-lmdb/src/store/lmdb/mod.rs
Closes https://gitworkshop.dev/yukikishimoto.com/nostr/issues/note1fll6m4eh82m2jdy2tjcvk5e6uj5nd67w2lw4rnjw9su83qerg9wq4cy9xt
=> lmdb: improve performance of queries with authors, kinds and tags
